/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSimulationsRouteImport } from './routes/api/simulations'
import { Route as ApiEnrollmentsRouteImport } from './routes/api/enrollments'
import { Route as ApiSimulationsIdRouteImport } from './routes/api/simulations.$id'
import { Route as ApiEnrollmentsIdRouteImport } from './routes/api/enrollments.$id'

const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulationsRoute = ApiSimulationsRouteImport.update({
  id: '/api/simulations',
  path: '/api/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrollmentsRoute = ApiEnrollmentsRouteImport.update({
  id: '/api/enrollments',
  path: '/api/enrollments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulationsIdRoute = ApiSimulationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSimulationsRoute,
} as any)
const ApiEnrollmentsIdRoute = ApiEnrollmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEnrollmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/simulations': typeof SimulationsRoute
  '/api/enrollments': typeof ApiEnrollmentsRouteWithChildren
  '/api/simulations': typeof ApiSimulationsRouteWithChildren
  '/api/enrollments/$id': typeof ApiEnrollmentsIdRoute
  '/api/simulations/$id': typeof ApiSimulationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/simulations': typeof SimulationsRoute
  '/api/enrollments': typeof ApiEnrollmentsRouteWithChildren
  '/api/simulations': typeof ApiSimulationsRouteWithChildren
  '/api/enrollments/$id': typeof ApiEnrollmentsIdRoute
  '/api/simulations/$id': typeof ApiSimulationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/simulations': typeof SimulationsRoute
  '/api/enrollments': typeof ApiEnrollmentsRouteWithChildren
  '/api/simulations': typeof ApiSimulationsRouteWithChildren
  '/api/enrollments/$id': typeof ApiEnrollmentsIdRoute
  '/api/simulations/$id': typeof ApiSimulationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/simulations'
    | '/api/enrollments'
    | '/api/simulations'
    | '/api/enrollments/$id'
    | '/api/simulations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/simulations'
    | '/api/enrollments'
    | '/api/simulations'
    | '/api/enrollments/$id'
    | '/api/simulations/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/simulations'
    | '/api/enrollments'
    | '/api/simulations'
    | '/api/enrollments/$id'
    | '/api/simulations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SimulationsRoute: typeof SimulationsRoute
  ApiEnrollmentsRoute: typeof ApiEnrollmentsRouteWithChildren
  ApiSimulationsRoute: typeof ApiSimulationsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulations': {
      id: '/api/simulations'
      path: '/api/simulations'
      fullPath: '/api/simulations'
      preLoaderRoute: typeof ApiSimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enrollments': {
      id: '/api/enrollments'
      path: '/api/enrollments'
      fullPath: '/api/enrollments'
      preLoaderRoute: typeof ApiEnrollmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulations/$id': {
      id: '/api/simulations/$id'
      path: '/$id'
      fullPath: '/api/simulations/$id'
      preLoaderRoute: typeof ApiSimulationsIdRouteImport
      parentRoute: typeof ApiSimulationsRoute
    }
    '/api/enrollments/$id': {
      id: '/api/enrollments/$id'
      path: '/$id'
      fullPath: '/api/enrollments/$id'
      preLoaderRoute: typeof ApiEnrollmentsIdRouteImport
      parentRoute: typeof ApiEnrollmentsRoute
    }
  }
}

interface ApiEnrollmentsRouteChildren {
  ApiEnrollmentsIdRoute: typeof ApiEnrollmentsIdRoute
}

const ApiEnrollmentsRouteChildren: ApiEnrollmentsRouteChildren = {
  ApiEnrollmentsIdRoute: ApiEnrollmentsIdRoute,
}

const ApiEnrollmentsRouteWithChildren = ApiEnrollmentsRoute._addFileChildren(
  ApiEnrollmentsRouteChildren,
)

interface ApiSimulationsRouteChildren {
  ApiSimulationsIdRoute: typeof ApiSimulationsIdRoute
}

const ApiSimulationsRouteChildren: ApiSimulationsRouteChildren = {
  ApiSimulationsIdRoute: ApiSimulationsIdRoute,
}

const ApiSimulationsRouteWithChildren = ApiSimulationsRoute._addFileChildren(
  ApiSimulationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SimulationsRoute: SimulationsRoute,
  ApiEnrollmentsRoute: ApiEnrollmentsRouteWithChildren,
  ApiSimulationsRoute: ApiSimulationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
